### ISSUE TITLE
Students were not able to upload the csv file

### ISSUE THREAD

**Issue by Felipe-Hub** [ironhack-labs/lab-sql-6#1]
@sandrabosk 

Students were not able to upload the csv file to mysql, they had issues related to 'secure_file_priv', since you can only change this setting in my.ini (here is a possible, but not easy fix: https://stackoverflow.com/questions/32737478/how-should-i-tackle-secure-file-priv-in-mysql).
The students who were able to, already had a directory specified on 'secure_file_priv', so they could upload the csv file from that directory, but there were still some issues fitting the data in the film table (verify orignal_language_id and rental_rate columns).

The way around it was to create the films_2020 with CREATE TABLE and then import the csv file with the Data Import Wizard (https://community.jaspersoft.com/blog/mysql-workbench-table-data-import-and-export-procedure)

**Comment by haggarw3** [comment]
@Felipe-Hub
In the lesson we had provided the code to fix this issue related to 'secure_file_priv'
By default this option is off and we have to turn this ON using the code below 

show variables like 'local_infile';
set global local_infile = 1;

I have added this to the solutions. Now the students should be able to bulk insert in the tables in that database

**Comment by ironhack-edu** [comment]
Solution updated with Himanshu's code. Thank you. Changes merged.
