### ISSUE TITLE
solution does not work 

### ISSUE THREAD

**Issue by siandav** [ironhack-labs/lab-sql-6#4]
solution to use INSERT method for csv upload errors and fails.. this is because of the empty columns in the csv file. 

using the file>import method will work... but in mapping it is necessary to remove those columns or hard code the values 

i think this is because the suggested solution code is set for the pre existing film table, which will work... as it will pass by the empty columns. but as we are creating the film 2020 table we have a problem 

also the query to create this file includes enum, which we havent covered in class ... suggest removing this to avoid confusion 

@sandrabosk

**Comment by ironhack-edu** [comment]
@haggarw3 Please check this one when you find some time.
